version: 2

# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  environment:
    CI_SCRIPTS: 'npx --quiet --package @reactioncommerce/ci-scripts@1.6.2'
    DOCKER_REPOSITORY: "reactioncommerce/styleguide"
    DOCKER_NAMESPACE: "reactioncommerce"
    DOCKER_NAME: "styleguide"
  docker:
    - image: circleci/node:8.11.4-stretch

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-v3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-modules-v3-{{ .Branch }}
      - run:
          name: Install Style Guide NPM dependencies
          command: yarn install
      - run:
          name: Install Package NPM dependencies
          command: cd package && yarn install
      - save_cache:
          key: node-modules-v3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: node-modules-v3-{{ .Branch }}
          paths:
            - node_modules
      - save_cache:
          key: node-modules-package-v3-{{ checksum "package/package.json" }}-{{ checksum "package/yarn.lock" }}
          paths:
            - package/node_modules
      - save_cache:
          key: node-modules-package-v3-{{ .Branch }}
          paths:
            - package/node_modules

  dockerfile-lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Lint Dockerfiles
          command: ${CI_SCRIPTS} lint-dockerfiles

  eslint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-v3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-modules-v3-{{ .Branch }}
      - restore_cache:
          keys:
            - node-modules-package-v3-{{ checksum "package/package.json" }}-{{ checksum "package/yarn.lock" }}
            - node-modules-package-v3-{{ .Branch }}
      - run:
          name: Lint JavaScript
          command: yarn run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-v3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-modules-v3-{{ .Branch }}
      - restore_cache:
          keys:
            - node-modules-package-v3-{{ checksum "package/package.json" }}-{{ checksum "package/yarn.lock" }}
            - node-modules-package-v3-{{ .Branch }}
      - run:
          name: Run Unit Tests
          command: yarn run test

  docker-build-push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push production Docker image
          command: ${CI_SCRIPTS} docker-build-tag-push . ${DOCKER_REPOSITORY}

  publish-npm-package:
    docker:
      - image: node:8

    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    steps:
      - checkout

      - run: yarn install
      - run: cd package && yarn install
      - run: cd package && yarn run build
      - run: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies
      - dockerfile-lint
      - eslint:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - docker-build-push:
          context: reaction-publish-docker
          requires:
            - dockerfile-lint
            - eslint
            - test
      - publish-npm-package:
          context: reaction-publish-semantic-release
          requires:
            - dockerfile-lint
            - eslint
            - test
          filters:
            branches:
              only: master
